<?php
// public/appeal/index.php
// Appeal page for users whose comments have been hidden.
// URL: /appeal?token={signed_token}
// The token is generated by ModerationService::generateAppealToken()
// and embedded in the reply posted under the hidden comment on Facebook.

declare(strict_types=1);

require_once __DIR__ . '/../../vendor/autoload.php';

use Illuminate\Database\Capsule\Manager as DB;
use Dotenv\Dotenv;

// ── Bootstrap ─────────────────────────────────────────────────────────────
$dotenv = Dotenv::createImmutable(__DIR__ . '/../../');
$dotenv->safeLoad();

$capsule = new DB();
$capsule->addConnection([
    'driver'    => 'mysql',
    'host'      => $_ENV['DB_HOST']     ?? '127.0.0.1',
    'port'      => $_ENV['DB_PORT']     ?? '3306',
    'database'  => $_ENV['DB_DATABASE'] ?? 'moderation_hub',
    'username'  => $_ENV['DB_USERNAME'] ?? 'root',
    'password'  => $_ENV['DB_PASSWORD'] ?? '',
    'charset'   => 'utf8mb4',
    'collation' => 'utf8mb4_unicode_ci',
]);
$capsule->setAsGlobal();
$capsule->bootEloquent();

// ── Helpers ────────────────────────────────────────────────────────────────
function verifyToken(string $token): ?array
{
    try {
        $padded  = str_pad($token, strlen($token) + (4 - strlen($token) % 4) % 4, '=');
        $decoded = base64_decode($padded, strict: true);
        if ($decoded === false) return null;

        $parts = explode(':', $decoded, 4);
        if (count($parts) !== 4) return null;
        [$commentId, $socialUserId, $expires, $sig] = $parts;

        // No weak fallback: without a real secret, fail closed (tokens must be unforgeable).
        $secret = (string) ($_ENV['APP_SECRET'] ?? '');
        if ($secret === '') return null;
        $payload  = "{$commentId}:{$socialUserId}:{$expires}";
        $expected = hash_hmac('sha256', $payload, $secret);

        if (!hash_equals($expected, $sig))      return null;
        if ((int) $expires < time())            return null;

        return ['comment_id' => (int) $commentId, 'social_user_id' => (int) $socialUserId];
    } catch (\Throwable) {
        return null;
    }
}

function h(string $s): string
{
    return htmlspecialchars($s, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8');
}

// ── Route logic ────────────────────────────────────────────────────────────
$token  = trim($_GET['token'] ?? '');
$error  = null;
$success = null;
$comment = null;
$alreadyAppealed = false;

if (empty($token)) {
    $error = 'Link non valido o scaduto.';
} else {
    $decoded = verifyToken($token);

    if (!$decoded) {
        $error = 'Il link di ricorso non è valido oppure è scaduto (validità 30 giorni).';
    } else {
        $comment = DB::table('comments')
            ->where('id', $decoded['comment_id'])
            ->where('appeal_token', $token)
            ->first();

        if (!$comment) {
            $error = 'Commento non trovato o link già utilizzato.';
        } elseif (!in_array($comment->status, ['hidden', 'hidden_reportable'], true)) {
            // Comment was already restored or removed — appeal no longer needed
            if ($comment->status === 'approved') {
                $success = 'Il tuo commento è già stato ripristinato. Grazie per la pazienza.';
            } else {
                $error = 'Non è possibile presentare ricorso per questo commento nel suo stato attuale.';
            }
        } else {
            // Check if appeal was already submitted
            $existing = DB::table('appeal_records')
                ->where('comment_id', $decoded['comment_id'])
                ->where('social_user_id', $decoded['social_user_id'])
                ->first();

            if ($existing) {
                $alreadyAppealed = true;
                $appealStatus    = $existing->status;
            }
        }
    }
}

// ── Handle POST (appeal submission) ───────────────────────────────────────
if ($_SERVER['REQUEST_METHOD'] === 'POST' && $comment && !$alreadyAppealed && !$error) {
    $appealText = trim($_POST['appeal_text'] ?? '');

    if (strlen($appealText) < 10) {
        $error = 'Inserisci una motivazione di almeno 10 caratteri.';
    } elseif (strlen($appealText) > 2000) {
        $error = 'La motivazione non può superare i 2000 caratteri.';
    } else {
        $decoded = verifyToken($token);
        DB::table('appeal_records')->insert([
            'comment_id'     => $decoded['comment_id'],
            'social_user_id' => $decoded['social_user_id'],
            'appeal_text'    => $appealText,
            'status'         => 'pending',
            'submitted_at'   => date('Y-m-d H:i:s'),
        ]);

        // Flag comment with dedicated appeal status — kept OUT of the normal
        // human review queue, managed exclusively from the Appeals tab.
        DB::table('comments')
            ->where('id', $decoded['comment_id'])
            ->update(['status' => 'appeal_pending']);

        $success = 'Il tuo ricorso è stato inviato. I nostri moderatori lo esamineranno al più presto.';
        $alreadyAppealed = true;
    }
}

// ── Render ─────────────────────────────────────────────────────────────────
$siteName = $_ENV['SITE_NAME'] ?? 'Moderation Hub';
?>
<!DOCTYPE html>
<html lang="it">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Ricorso commento – <?= h($siteName) ?></title>
  <link rel="icon" type="image/svg+xml" href="/favicon.svg">
  <style>
    *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }

    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
      background: #f4f6f9;
      color: #1a1a2e;
      min-height: 100vh;
      display: flex;
      align-items: center;
      justify-content: center;
      padding: 24px 16px;
    }

    .card {
      background: #fff;
      border-radius: 16px;
      box-shadow: 0 4px 24px rgba(0,0,0,.10);
      max-width: 520px;
      width: 100%;
      padding: 40px 36px;
    }

    .logo {
      font-size: 13px;
      font-weight: 600;
      color: #6b7280;
      text-transform: uppercase;
      letter-spacing: .08em;
      margin-bottom: 28px;
    }

    h1 {
      font-size: 22px;
      font-weight: 700;
      margin-bottom: 10px;
      line-height: 1.3;
    }

    .subtitle {
      font-size: 14px;
      color: #6b7280;
      line-height: 1.6;
      margin-bottom: 28px;
    }

    .alert {
      border-radius: 10px;
      padding: 14px 16px;
      font-size: 14px;
      line-height: 1.5;
      margin-bottom: 20px;
    }
    .alert-error   { background: #fef2f2; color: #991b1b; border: 1px solid #fecaca; }
    .alert-success { background: #f0fdf4; color: #166534; border: 1px solid #bbf7d0; }
    .alert-info    { background: #eff6ff; color: #1e40af; border: 1px solid #bfdbfe; }

    .comment-box {
      background: #f8fafc;
      border: 1px solid #e2e8f0;
      border-radius: 10px;
      padding: 14px 16px;
      font-size: 14px;
      line-height: 1.6;
      color: #374151;
      margin-bottom: 24px;
      font-style: italic;
    }
    .comment-label {
      font-size: 11px;
      font-weight: 600;
      color: #9ca3af;
      text-transform: uppercase;
      letter-spacing: .06em;
      margin-bottom: 6px;
    }

    label {
      display: block;
      font-size: 13px;
      font-weight: 600;
      color: #374151;
      margin-bottom: 6px;
    }

    textarea {
      width: 100%;
      border: 1px solid #d1d5db;
      border-radius: 8px;
      padding: 12px 14px;
      font-size: 14px;
      font-family: inherit;
      resize: vertical;
      min-height: 110px;
      color: #1a1a2e;
      transition: border-color .2s;
      outline: none;
    }
    textarea:focus { border-color: #6366f1; box-shadow: 0 0 0 3px rgba(99,102,241,.12); }

    .char-count {
      font-size: 11px;
      color: #9ca3af;
      text-align: right;
      margin-top: 4px;
      margin-bottom: 20px;
    }

    button[type="submit"] {
      width: 100%;
      background: #6366f1;
      color: #fff;
      border: none;
      border-radius: 8px;
      padding: 13px 20px;
      font-size: 15px;
      font-weight: 600;
      cursor: pointer;
      transition: background .2s, transform .1s;
    }
    button[type="submit"]:hover  { background: #4f46e5; }
    button[type="submit"]:active { transform: scale(.98); }
    button[type="submit"]:disabled { background: #c7d2fe; cursor: not-allowed; }

    .footer {
      margin-top: 28px;
      font-size: 12px;
      color: #9ca3af;
      line-height: 1.5;
      text-align: center;
    }

    .badge {
      display: inline-flex;
      align-items: center;
      gap: 5px;
      background: #fef3c7;
      color: #92400e;
      border-radius: 6px;
      padding: 4px 10px;
      font-size: 12px;
      font-weight: 600;
      margin-bottom: 20px;
    }
  </style>
</head>
<body>
<div class="card">
  <div class="logo"><?= h($siteName) ?></div>

  <?php if ($error): ?>
    <h1>Link non valido</h1>
    <div class="alert alert-error"><?= h($error) ?></div>
    <p class="subtitle">Se hai ricevuto questo link via Facebook e ritieni ci sia un errore, contatta la redazione direttamente sulla pagina.</p>

  <?php elseif ($success): ?>
    <h1>✓ Ricorso inviato</h1>
    <div class="alert alert-success"><?= h($success) ?></div>
    <p class="subtitle">Riceverai una notifica sulla tua pagina Facebook una volta che il moderatore avrà esaminato il tuo ricorso.</p>

  <?php elseif ($alreadyAppealed): ?>
    <h1>Ricorso già inviato</h1>
    <?php if (($appealStatus ?? '') === 'pending'): ?>
      <div class="alert alert-info">Il tuo ricorso è in attesa di revisione da parte di un moderatore. Ti risponderemo il prima possibile.</div>
    <?php elseif (($appealStatus ?? '') === 'rejected'): ?>
      <div class="alert alert-error">Il tuo ricorso è stato esaminato e la decisione di nascondere il commento è stata confermata.</div>
    <?php endif; ?>

  <?php elseif ($comment): ?>
    <h1>Richiedi revisione del commento</h1>
    <p class="subtitle">Il tuo commento è stato temporaneamente nascosto dalla nostra redazione. Se ritieni che la decisione sia errata, puoi presentare un ricorso qui sotto.</p>

    <?php if ($comment->status === 'hidden_reportable'): ?>
      <div class="badge">⚠️ Contenuto segnalato per valutazione legale</div>
    <?php endif; ?>

    <div class="comment-label">Il tuo commento</div>
    <div class="comment-box"><?= h($comment->content) ?></div>

    <form method="POST" action="">
      <input type="hidden" name="token" value="<?= h($token) ?>">
      <label for="appeal_text">Perché ritieni che il commento non violi le nostre linee guida?</label>
      <textarea
        id="appeal_text"
        name="appeal_text"
        maxlength="2000"
        placeholder="Spiega brevemente il contesto o le tue ragioni…"
        oninput="document.getElementById('cc').textContent = this.value.length + '/2000'"
        required
      ></textarea>
      <div class="char-count"><span id="cc">0</span>/2000</div>
      <button type="submit">Invia ricorso</button>
    </form>

  <?php endif; ?>

  <div class="footer">
    Questo sistema di moderazione è gestito dalla redazione di <?= h($siteName) ?>.<br>
    Le decisioni di moderazione seguono le nostre <a href="/privacy" style="color:#6366f1">linee guida della community</a>.
  </div>
</div>
</body>
</html>